import {  Comic_Neue } from 'next/font/google'
import './globals.css'

const comic = Comic_Neue({ subsets: ['latin'] , weight: ['300', '400', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comic.className}>{children}</body>
    </html>
  )
}
